### ISSUE TITLE
package.json is incorrect

### ISSUE THREAD

**Issue by ericeslinger** [thgreasi/localForage-setItems#1]
Similar to the issue in localForage-setItems, there's a case-sensitivity mixup here:

https://github.com/localForage-extensions/localForage-setItems/blob/master/package.json#L35

**Comment by thgreasi** [comment]
Nice catch :+1: If you can open a PR, I can merge it ASAP.

**Comment by thgreasi** [comment]
Just pushed v1.2 that uses es6 modules and rollup. I think that this can be closed now. Please confirm that it works for you.
