### ISSUE TITLE
Reference to '../../utils/serializer'

### ISSUE THREAD

**Issue by ericeslinger** [thgreasi/localForage-setItems#2]
I'm trying to use this library in my browserify-compiled, ES6-modules-using library. Browserify chokes on:

https://github.com/localForage-extensions/localForage-setItems/blob/master/src/localforage-setitems.js#L194

with a basic not found error at build time. Is there another / better place to pull the default serializer from?

**Comment by thgreasi** [comment]
Thanks for reporting, I will try to upgrade this lib, to use the new localforage.getSerializer() API (v1.3+).
Does this sounds fine with you?

**Comment by ericeslinger** [comment]
yup, that's fine with me (personally) - I've been using ~1.4.0 of localforage recently. In the meantime I just hacked up a copy that only does the batch get/set actions on indexeddb, since the serializer is only required for webSQL stuff.

**Comment by thgreasi** [comment]
:+1: for your hacky solution!
I will try to fix it tomorrow and by the way, I will upgrade the code to use the [localForage-plugin-boilerplate](https://github.com/localForage-extensions/localForage-plugin-boilerplate).

**Comment by thgreasi** [comment]
Just pushed v1.2 that uses es6 modules and rollup. I think that this can be closed now. Please confirm that it works for you.
